const strings = {
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  WELCOME_LOGIN: 'Welcome Back',
  GET_STARTED: 'Get Started',
  SIGN_IN_TO_CONTINUE: 'Sign in to continue',
  FORGOT_PASSWORD: 'Forgot Password?',
  RESET_PASSWORD: 'Reset Password',
  BACK: 'Back',
  SKIP: 'Skip',
  SUBMIT: 'Submit',
  CONTINUE: 'Continue',
  SIGN_UP: 'Sign Up',
  SIGN_IN: 'Sign In',
  VERIFY: 'Verify',
  SEND: 'Send',
  BACK_TO_LOGIN: 'Back to login',
  CONSTRUCTION_PROGRESS: 'Construction Progress',
  EMAIL_ID: ' Email ID ',
  PASSWORD: ' Password ',
  CONFIRM_PASSWORD: ' Confirm Password ',
  CURRENT_PASSWORD: ' Current Password ',
  NEW_PASSWORD: ' New Password ',
  VERIFICATION_CODE: ' Verification Code ',
  HOME_BUILDER: ' Home Builder ',
  MODEL_HOME: ' Model Home ',
  FIRST_NAME: ' First Name ',
  LAST_NAME: ' Last Name ',
  PHONE: ' Phone ',
  ADDRESS: ' Address ',
  CITY: ' City ',
  STATE: ' State ',
  LOCATION: ' Location ',
  SHARE_FEEDBACK: ' Share your Feedback ',
  COPY_RIGHT: '© Copyright NEXTPORT - All Rights Reserved',
  SLIDE1_TILE: 'Congratulations',
  SLIDE1_DESC:
    'You are about to embark on an amazing journey to create a home for you and your loved ones.',
  SLIDE2_TILE: 'Building Your Dream Home',
  SLIDE2_DESC:
    'You are not just building a home, you will be building family memories.',
  SLIDE3_TILE: 'This is Exciting',
  SLIDE3_DESC:
    'We share your excitement, and we will keep you up-to-date about the progress of your dream home.',
  NEVER_MISS: 'Never Miss An Update!',
  NEVER_MISS_DESC:
    'Sign-up and get real-time updates on the constrution status of your brand new home',
  SIGN_UP_DESC1: 'Please reset your temporary password ',
  SIGN_UP_HEADING: 'You Are Almost There',
  TERMS_AND_CONDITION: 'By continuing you agree to our',
  TERMS_OF_SERVICE: 'Terms of Service',
  PRIVACY_POLICY: 'Privacy Policy',
  VALIDATION_REQUIREMENTS: 'Requirements',
  VALIDATION1: 'At Least 8 Characters Long',
  VALIDATION2: 'Combination of Uppercase and Lowercase letters',
  VALIDATION3: 'At Least a number',
  VALIDATION4: 'At Least a special character',
  CONFIRM_SIGNUP_HEADING: 'Please Verify your Email Address',
  CONFIRM_SIGNUP_DESC1: 'Please enter the OTP to verify your account.',
  CONFIRM_SIGNUP_DESC2: 'OTP has been sent to your registered email address.',
  RESEND_DESC: "If you don't recieve the code!",
  RESEND: 'Resend',
  SUCCESSPAGE_DESC1: 'Your account has been Successfully verified',
  SUCCESSPAGE_DESC2: 'Please login to continue',
  SUCCES_TITLE: 'Successfully verified',
  FORGOT_PASSWORD_DESC:
    'Enter the email address associated with your account. We will email you a link to reset your password',
  RESET_PASSWORD_DESC:
    'We will email you a verification code to reset your password.',
  RESET_PASSWORD_SUCCES: 'Password Reset Successful',
  RESET_PASSWORD_SUCCESPAGE_DESC:
    'You can now use your new password to login in to your account',
  HOME_TAB_LABEL: 'Home',
  CALANDAR_TAB_LABEL: 'Calendar',
  ALERTS_TAB_LABEL: 'Alerts',
  PROFILE_TAB_LABEL: 'Me',
  PROFILE: 'Profile',
  HI: 'Hi ',
  HOME_DESC: 'Check the status of your project.',
  HOME_CARD1: 'Media Library',
  HOME_CARD2: 'Stay Informed',
  HOME_CARD3: 'Construction Calendar',
  HOME_CARD4: 'Finances',
  COMMING_SOON: 'Coming Soon',
  PRE_CONSTRUCTION: 'Pre-construction',
  CLOSING: 'Closing',
  UPCOMMING_MEETING: 'Upcoming Meeting',
  NO_UPCOMMING_MEETING: 'No Upcoming Meetings Yet...',
  PREVIOUS_MEETING: 'Previous Meetings',
  NO_PREVIOUS_MEETING: 'No Previous Meetings Yet...',
  VIEW_DETAILS: 'View Details',
  STATUS_SCHEDULE: 'Scheduled',
  STATUS_TO_SCHEDULE: 'To Schedule',
  STATUS_RE_SCHEDULE: 'Re scheduled',
  STATUS_CANCEL: 'Cancelled',
  STATUS_ACCEPT: 'Accepted',
  ACCEPT: 'Accept',
  CANCEL: 'Cancel',
  CLOSE: 'Close',
  SAVE: 'Save',
  APPLY: 'Apply',
  RE_SCHEDULE: 'Reschedule',
  MEETING_DATE: 'Meeting Date',
  TIME: 'Time',
  PHONE_NUMBER: 'Phone Number',
  ADD_TO_CALENDAR: 'Add to calendar',
  NO_ALERTS: 'No Alerts !',
  GO_TO_HOME: 'Go to Home',
  VIEW_PHOTOS: 'View Photos',
  VIEW_PROFILE: 'View Profile',
  NEW_HOME: 'My New Home',
  NOTIFICATIONS: 'Notifications',
  CUSTOMER_SUPPORT: 'Customer Support',
  PHOTOS: 'Photos',
  FEEDBACK: 'Feedback',
  DISCLAIMER: 'Disclaimers',
  DOCUMENTS: 'Documents',
  WEB: 'Web',
  CHANGE_PASSWORD: 'Change Password',
  SUPPORT_PAGE_DES1: 'Construction Questions?',
  SUPPORT_PAGE_DES2: 'Contact your customer service Representative',
  TEXT: 'Text',
  EMAIL: ' Email ',
  CALL: 'Call',
  GIVE_FEEDBACK: 'Give Us Feedback',
  FEEDBACK_DESC: 'What Type Of Feedback Would You Like To Provide ?',
  RADIO_BUTTON1: 'App Issues',
  RADIO_BUTTON2: 'Construction Feedback',
  RADIO_BUTTON3: 'Suggest Features',
  FEEDBACK_CONFIRM: 'Thanks For Your FeedBack',
  FEEDBACK_CONFIRM_DESC1:
    'We really appreciate you taking the time to share your feedback with us.',
  FEEDBACK_CONFIRM_DESC2:
    'Your opinion is valued greatly and it helps us maintain excellent standard of service to our customers.',
  PLANS: 'Plans',
  NO_PLANS: 'No floor plans found',
  FLOOR_PLAN: 'Floor Plan',
  MAP: 'Map',
  STAY_INFORM: 'Stay Informed',
  NOTIFICATION_MOB: 'Mobile App Notifications',
  NOTIFICATION_MOB_DESC: 'Get alert about your home via the app',
  NOTIFICATION_TEXT: 'Text Notifications',
  NOTIFICATION_TEXT_DESC: 'Receive text notifications',
  PHOTOS_HEADING: 'Access Your Photos and Video Gallery',
  NO_MEDIA_FOUND: 'No media found for ',
  NO_ITEM_FOUND: ' No media found for your project',
  PDF_ITEM: 'PdfItem',
  IMAGE_LOADING: 'Loading Image',
  IN_PROGRESS: 'In Progress...',
  MEETING_SCHEDULED: 'Meeting Scheduled',
  TOPIC: 'Topic',
  DESCRIPION: 'Description ',
  DURATION: 'Duration',
  TIME_ZONE: 'Time Zone',
  MEETING_LINK: 'Meeting Link',
  CONSTRUCTION_CALENDAR_TITLE1: 'See What We Are Working On',
  CONSTRUCTION_CALENDAR_TITLE2: 'See What Is Happening Next Week',
  CONSTRUCTION_CALENDAR_TITLE3: 'Access All Your Construction History',
  CONSTRUCTION_CALENDAR_DESC1: 'Drywall Installation',
  CONSTRUCTION_CALENDAR_DESC2: 'Next week, we are scheduled to install drywall',
  FINANCE_TITLE1: 'Stay On Top Of Your Budget',
  FINANCE_TITLE2: 'Have Visibility Of All Your Approved Upgrades',
  FINANCE_TITLE3: 'Calculate Your Monthly Payments',
  ROTATE: 'Rotate',
  CONSTRUCTION_CALENDAR: 'Construction Calendar',
  NO_SUB_TASK: 'No Sub Task added yet',
  NO_DATA_FOUND: 'No data found...',
  START_DATE: 'Start Date: ',
  END_DATE: 'End Date: ',
  PROFILE_PHOTO: 'Profile Photo',
  GALLERY: 'Gallery',
  REMOVE_PIC: 'Remove Photo',
  NO_INTERNET: 'No Internet!',
  NO_INTERNET_DESC1: 'Slow or no internet connection',
  NO_INTERNET_DESC2: 'Please check your internet connection',
  RETRY: 'Retry',
  EMPTY_FEEDBACK: 'No replys yet.',
  NOT_SEND_FEEDBACK: 'You have not sent any feedback yet.',
  VIEW_HISTORY: 'View History',
  MEETINGS: 'Meetings',
  SORT: 'Sorting',
  NO_FEEDBACK: 'Please Share Your Feedback',
  COMPLETED: 'Completed',
  WEEKS_LEFT: 'Weeks Left',
  PRJ_FINANCE: 'Project Finances',
  FINANCE_1: 'Original Contract',
  FINANCE_2: 'Approved Change Orders',
  FINANCE_3: 'Revised Contract',
  FINANCE_4: 'Pending Revised Contract',
  FINANCE_5: 'Pending Change Orders',
  FINANCE_6: 'Draft Change Orders',
  FINANCE_7: 'Owner Invoices',
  FINANCE_8: 'Payments Received',
  FINANCE_9: 'Percent Paid',
  FINANCE_10: 'Remaining Balance Outstanding',
};

export default strings;
